/*
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.skem.ui.internal.SkemActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(SkemActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		SkemActivator activator = SkemActivator.getInstance();
		return activator != null ? activator.getInjector(SkemActivator.ORG_XTEXT_EXAMPLE_MYDSL_MYDSL) : null;
	}

}
