/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Arguments</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Arguments#getVarA <em>Var A</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getArguments()
 * @model
 * @generated
 */
public interface Arguments extends EObject
{
  /**
   * Returns the value of the '<em><b>Var A</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var A</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var A</em>' attribute.
   * @see #setVarA(int)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getArguments_VarA()
   * @model
   * @generated
   */
  int getVarA();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Arguments#getVarA <em>Var A</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var A</em>' attribute.
   * @see #getVarA()
   * @generated
   */
  void setVarA(int value);

} // Arguments
