/**
 * generated by Xtext 2.13.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Variable#getVarB <em>Var B</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getVariable()
 * @model
 * @generated
 */
public interface Variable extends Arguments
{
  /**
   * Returns the value of the '<em><b>Var B</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var B</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var B</em>' attribute.
   * @see #setVarB(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getVariable_VarB()
   * @model
   * @generated
   */
  String getVarB();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Variable#getVarB <em>Var B</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var B</em>' attribute.
   * @see #getVarB()
   * @generated
   */
  void setVarB(String value);

} // Variable
